---
development:
  cloud_name: loboarcano
  api_key: '885726863642699'
  api_secret: '08PO0iqpwz_7pakeO9m6BxVL1bw'
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: loboarcano
  api_key: '885726863642699'
  api_secret: '08PO0iqpwz_7pakeO9m6BxVL1bw'
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: loboarcano
  api_key: '885726863642699'
  api_secret: '08PO0iqpwz_7pakeO9m6BxVL1bw'
  enhance_image_tag: true
  static_file_support: false
